[package]
name = "cmdplus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
filetime = "0.2.25"
predicates = "3.1.3"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.19.1"
predicates = "3.1.3"

[lib]
name = "cmdplus"
path = "src/lib.rs"