name: Deploy Rust Docs to GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  contents: write       # リポジトリへのファイル書き込みを許可
  pages: write          # GitHub Pages API へのデプロイ権限を許可
  id-token: write       # OIDC トークン取得のために必要

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./target/doc/cmdplus
          publish_branch: gh-pages
